development:
  adapter: postgresql
  database: uniquelyphilly_development
  username: uniquelyphilly
  password: ENV['PG_PW']
  host: localhost 

production:
  adapter: postgresql
  database: uniquelyphilly_development
  username: uniquelyphilly
  password: ENV['PG_PW']
  host: localhost 